services:
  postgres_db:
    restart: unless-stopped
    image: opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/postgres
    volumes:
      - postgres_db:/var/lib/postgresql/data
    command: -p ${DATABASE_PORT}
    environment:
      - POSTGRES_DB=${DATABASE_DB}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    env_file:
      - .env
    expose: 
      - ${DATABASE_PORT}
    ports:
      - "5433:${DATABASE_PORT}"
  celery_redis:
    restart: unless-stopped
    image: redis:latest  # 使用配置好的镜像
    volumes:
      - celery_redis_data:/data  # 挂载数据卷以持久化 Redis 数据
    ports:
      - "6379:6379"  # 将主机的 6379 端口映射到容器的 6379 端口
  celery_worker1:
    restart: unless-stopped
    image: opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/dataflow  # 使用配置好的镜像
    env_file:
      - .env
    command: >
      sh -c "
        celery -A data_celery.main:celery_app worker --loglevel=info --pool=eventlet -n NODENAME1
      "
    depends_on:
      - celery_redis

  api_server:
    build: .
    env_file:
      - .env
    volumes:
      # - .:/dataflow
      - ${DATA_DIR}:${DATA_DIR}
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    # command: ["uvicorn", "data_server.main:app", "--host", "0.0.0.0", "--port", "8000"]
volumes:
  postgres_db:
  celery_redis_data:
